name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Enable caching
      uses: actions/cache@v2
      with:
        path: '~/node_modules'
        key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install
      run: npm install
    - name: Build
      run: npm run build --if-present
      env:
          CI: true
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: '~/node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm install
      - name: Testing
        run: npm run test
        env:
            CI: true
  lint:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: '~/node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Stylelint
        run: npm run stylelint
        env:
            CI: true
